import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ReactQueryClient from "@/components/container/ReactQueryClient";

import "./globals.css";
import NavbarLanding from "@/components/sections/NavbarLanding";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryClient>
        <body className={inter.className}>
          <NavbarLanding />
          {children}
        </body>
      </ReactQueryClient>
    </html>
  );
}
